# -*- coding: utf-8 -*-
{
    'name': "TMR VSDC Connector",
    'summary': """Connects Odoo to VSDC""",
    'description': """A custom module that adds the RRA CIS specifications to Odoo""",
    'author': "Hyperthink Systems Kenya",
    'website': "https://www.hyperthinkkenya.co.ke",
    'category': 'Hidden',
    'version': '15.0.1.0.1',
    'depends': [
        'contacts',
        'account',
        'purchase_stock',
        'sale_stock',
        'point_of_sale',
        'account_reports',
        'cis'
    ],

    'data': [
        'data/ir_sequence_data.xml',
        'data/cis_data.xml',
        'views/account_views.xml',
        'views/product_views.xml',
        'views/pos_order_views.xml',
        'views/account_recv_views.xml',
        'views/report_invoice.xml',
        'wizard/message_wizard.xml',
        'wizard/adjustment_vsdc_data_wizard.xml',
        'wizard/account_move_reversal_view.xml',
        'views/res_users_views.xml',
        'views/res_company_views.xml',
        'views/res_partner_views.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/report_financial.xml',
        'views/stock_views.xml',
        'views/sdc_log_views.xml',
        'views/stock_picking_views.xml',
        'views/stock_quant_views.xml',
        'views/sale_order_views.xml',
        'views/vsdc_products_import_views.xml',
    ],
    'assets': {
        'point_of_sale.assets': [
            'vsdc_connector/static/src/css/popups/common.css',
            'vsdc_connector/static/src/scss/style.scss',
            'vsdc_connector/static/src/js/Popups/TextAreaPopup.js',
            'vsdc_connector/static/src/js/Popups/ReasonLine.js',
            'vsdc_connector/static/src/js/models.js',
            'vsdc_connector/static/src/js/ProductScreen.js',
            'vsdc_connector/static/src/js/PaymentScreen.js',
            'vsdc_connector/static/src/js/OrderReceipt.js',
            'vsdc_connector/static/src/js/ReprintReceiptButton.js',
            'vsdc_connector/static/src/js/TicketScreen.js',
            'vsdc_connector/static/src/js/StockPopup.js',
            'vsdc_connector/static/src/js/Screens/ClientListScreen/ClientDetailsEdit.js',
            'https://cdnjs.cloudflare.com/ajax/libs/qrious/4.0.2/qrious.min.js'
        ],
        'web.assets_backend': [
            'vsdc_connector/static/src/js/button.js',
        ],
        'web.assets_qweb': [
            'vsdc_connector/static/src/xml/*',
            'vsdc_connector/static/src/xml/Screens/ClientListScreen/ClientDetailsEdit.xml',
            'vsdc_connector/static/src/xml/Popups/TextAreaPopup.xml',
            'vsdc_connector/static/src/xml/Popups/ReasonLine.xml',
        ],
    },
    'license': 'OPL-1',
    'application': True,
    'installable': True,
    'auto_install': False
}
